# Generated by Django 6.0.4 on 2026-06-19 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("authors", models.CharField(max_length=200)),
                ("publisher", models.CharField(max_length=100)),
                ("thumbnail", models.URLField(blank=True)),
                ("isbn", models.CharField(blank=True, max_length=50)),
                ("original_price", models.PositiveIntegerField(default=0)),
                ("price", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "거래가능"),
                            ("reserved", "예약중"),
                            ("done", "거래완료"),
                        ],
                        default="available",
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=100)),
                ("condition", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TradeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="books.book",
                    ),
                ),
            ],
        ),
    ]
