# Generated by Django 6.0.4 on 2026-06-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="trade_type",
            field=models.CharField(
                choices=[("sell", "팔아요"), ("exchange", "바꿔요"), ("free", "드려요")],
                default="sell",
                max_length=10,
            ),
        ),
    ]
